from typing import Any, Callable, Optional, Tuple, List, TypeAlias

# Type aliases matching C++ binding types
TLit: TypeAlias = int
TLiterals: TypeAlias = List[TLit]
TWLit: TypeAlias = Tuple[int, TLit]
TWLiterals: TypeAlias = List[TWLit]


class Solver:
    def __init__(self, sat_solver: str = ...) -> None: ...

    def add_clause(self, clause: TLiterals) -> bool: ...

    def solve(self, assumptions: TLiterals = ...) -> bool: ...

    def get_latest_solve_status(self) -> str: ...

    def get_latest_solution(self) -> TLiterals: ...

    def new_var(self) -> TLit: ...

    def max_var(self) -> TLit: ...

    def lit_value(self, lit: TLit) -> TLit: ...

    def get_verbosity_level(self) -> int: ...

    def set_verbosity_level(self, level: int) -> None: ...

    def set_enable_output_coloring(self, enable: bool) -> None: ...

    def get_latest_error_reason(self) -> str: ...

    def set_param(self, param_name: str, value: Any) -> None: ...

    def get_totalizer(self, lits: TLiterals, selector: Optional[TLit], rhs_simplification: Optional[int] = ...) -> TLiterals: ...

    def get_gen_totalizer(self, wlits: TWLiterals, selector: Optional[TWLit], rhs_simplification: Optional[int] = ...) -> TWLiterals: ...

    def add_constraint_less_than(self, lits: TLiterals, rhs: int, selector: Optional[TLit] = ...) -> bool: ...

    def add_constraint_less_than_equal(self, lits: TLiterals, rhs: int, selector: Optional[TLit] = ...) -> bool: ...

    def add_constraint_equal(self, lits: TLiterals, rhs: int, selector: Optional[TLit] = ...) -> bool: ...

    def add_constraint_greater_than_equal(self, lits: TLiterals, rhs: int, selector: Optional[TLit] = ...) -> bool: ...

    def add_constraint_greater_than(self, lits: TLiterals, rhs: int, selector: Optional[TLit] = ...) -> bool: ...

    def add_constraint_less_than(self, wlits: TWLiterals, rhs: int, selector: Optional[TLit] = ...) -> bool: ...

    def add_constraint_less_than_equal(self, wlits: TWLiterals, rhs: int, selector: Optional[TLit] = ...) -> bool: ...

    def get_latest_maxsat_value(self) -> int: ...

    def is_latest_maxsat_optimal(self) -> bool: ...

    def is_latest_maxsat_fixed_model_value(self) -> bool: ...

    def solve_maxsat(self, assumptions: TLiterals, soft_lits: TLiterals, fix_model_value: bool, callback_on_solution_found: Optional[Callable[[TLiterals], bool]] = ...) -> bool: ...

    def solve_weighted_maxsat(self, assumptions: TLiterals, soft_wlits: TWLiterals, fix_model_value: bool, callback_on_solution_found: Optional[Callable[[TWLiterals], bool]] = ...) -> bool: ...

    def get_latest_black_box_value(self) -> int: ...

    def solve_black_box(self, assumptions: TLiterals, observables: TLiterals, pb_func: Callable[[TLit], int], callback_on_solution_found: Optional[Callable[[TLiterals], bool]] = ...) -> bool: ...

    def solve_obv(self, assumptions: TLiterals, targets: TLiterals) -> bool: ...


class lits(TLiterals): ...


class wlits(TWLiterals): ...


__all__ = ["Solver", "lits", "wlits", "TLit", "TLiterals", "TWLit", "TWLiterals"]
